apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping
  labels: 
     app: shipping

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: shipping

  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
      #Parametrizar:
        image: 198937174082.dkr.ecr.us-east-1.amazonaws.com/shipping:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1